# language setting
language: ruby

# build systems
os:
  - linux

# language versions
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0-p353
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.2.4
  - 2.3.0
  - jruby-head
  - ruby-head

# include
branches:
  only:
    - master

# notify
notifications:
     email:
         recipients:
             - develop@schlegel11.de
